# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gurumurt/DBPV/Dispatcher/openCLDispatcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gurumurt/DBPV/Dispatcher/openCLDispatcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gurumurt/DBPV/Dispatcher/openCLDispatcher/CMakeFiles /home/gurumurt/DBPV/Dispatcher/openCLDispatcher/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gurumurt/DBPV/Dispatcher/openCLDispatcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openCLDispatcher

# Build rule for target.
openCLDispatcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openCLDispatcher
.PHONY : openCLDispatcher

# fast build rule for target.
openCLDispatcher/fast:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/build
.PHONY : openCLDispatcher/fast

include/common/algebra/Operators.o: include/common/algebra/Operators.cpp.o

.PHONY : include/common/algebra/Operators.o

# target to build an object file
include/common/algebra/Operators.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Operators.cpp.o
.PHONY : include/common/algebra/Operators.cpp.o

include/common/algebra/Operators.i: include/common/algebra/Operators.cpp.i

.PHONY : include/common/algebra/Operators.i

# target to preprocess a source file
include/common/algebra/Operators.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Operators.cpp.i
.PHONY : include/common/algebra/Operators.cpp.i

include/common/algebra/Operators.s: include/common/algebra/Operators.cpp.s

.PHONY : include/common/algebra/Operators.s

# target to generate assembly for a file
include/common/algebra/Operators.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Operators.cpp.s
.PHONY : include/common/algebra/Operators.cpp.s

include/common/algebra/Pipeline.o: include/common/algebra/Pipeline.cpp.o

.PHONY : include/common/algebra/Pipeline.o

# target to build an object file
include/common/algebra/Pipeline.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Pipeline.cpp.o
.PHONY : include/common/algebra/Pipeline.cpp.o

include/common/algebra/Pipeline.i: include/common/algebra/Pipeline.cpp.i

.PHONY : include/common/algebra/Pipeline.i

# target to preprocess a source file
include/common/algebra/Pipeline.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Pipeline.cpp.i
.PHONY : include/common/algebra/Pipeline.cpp.i

include/common/algebra/Pipeline.s: include/common/algebra/Pipeline.cpp.s

.PHONY : include/common/algebra/Pipeline.s

# target to generate assembly for a file
include/common/algebra/Pipeline.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Pipeline.cpp.s
.PHONY : include/common/algebra/Pipeline.cpp.s

include/common/algebra/Types.o: include/common/algebra/Types.cpp.o

.PHONY : include/common/algebra/Types.o

# target to build an object file
include/common/algebra/Types.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Types.cpp.o
.PHONY : include/common/algebra/Types.cpp.o

include/common/algebra/Types.i: include/common/algebra/Types.cpp.i

.PHONY : include/common/algebra/Types.i

# target to preprocess a source file
include/common/algebra/Types.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Types.cpp.i
.PHONY : include/common/algebra/Types.cpp.i

include/common/algebra/Types.s: include/common/algebra/Types.cpp.s

.PHONY : include/common/algebra/Types.s

# target to generate assembly for a file
include/common/algebra/Types.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/algebra/Types.cpp.s
.PHONY : include/common/algebra/Types.cpp.s

include/common/runtime/Concurrency.o: include/common/runtime/Concurrency.cpp.o

.PHONY : include/common/runtime/Concurrency.o

# target to build an object file
include/common/runtime/Concurrency.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Concurrency.cpp.o
.PHONY : include/common/runtime/Concurrency.cpp.o

include/common/runtime/Concurrency.i: include/common/runtime/Concurrency.cpp.i

.PHONY : include/common/runtime/Concurrency.i

# target to preprocess a source file
include/common/runtime/Concurrency.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Concurrency.cpp.i
.PHONY : include/common/runtime/Concurrency.cpp.i

include/common/runtime/Concurrency.s: include/common/runtime/Concurrency.cpp.s

.PHONY : include/common/runtime/Concurrency.s

# target to generate assembly for a file
include/common/runtime/Concurrency.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Concurrency.cpp.s
.PHONY : include/common/runtime/Concurrency.cpp.s

include/common/runtime/Database.o: include/common/runtime/Database.cpp.o

.PHONY : include/common/runtime/Database.o

# target to build an object file
include/common/runtime/Database.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Database.cpp.o
.PHONY : include/common/runtime/Database.cpp.o

include/common/runtime/Database.i: include/common/runtime/Database.cpp.i

.PHONY : include/common/runtime/Database.i

# target to preprocess a source file
include/common/runtime/Database.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Database.cpp.i
.PHONY : include/common/runtime/Database.cpp.i

include/common/runtime/Database.s: include/common/runtime/Database.cpp.s

.PHONY : include/common/runtime/Database.s

# target to generate assembly for a file
include/common/runtime/Database.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Database.cpp.s
.PHONY : include/common/runtime/Database.cpp.s

include/common/runtime/Hashmap.o: include/common/runtime/Hashmap.cpp.o

.PHONY : include/common/runtime/Hashmap.o

# target to build an object file
include/common/runtime/Hashmap.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Hashmap.cpp.o
.PHONY : include/common/runtime/Hashmap.cpp.o

include/common/runtime/Hashmap.i: include/common/runtime/Hashmap.cpp.i

.PHONY : include/common/runtime/Hashmap.i

# target to preprocess a source file
include/common/runtime/Hashmap.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Hashmap.cpp.i
.PHONY : include/common/runtime/Hashmap.cpp.i

include/common/runtime/Hashmap.s: include/common/runtime/Hashmap.cpp.s

.PHONY : include/common/runtime/Hashmap.s

# target to generate assembly for a file
include/common/runtime/Hashmap.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Hashmap.cpp.s
.PHONY : include/common/runtime/Hashmap.cpp.s

include/common/runtime/Import.o: include/common/runtime/Import.cpp.o

.PHONY : include/common/runtime/Import.o

# target to build an object file
include/common/runtime/Import.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Import.cpp.o
.PHONY : include/common/runtime/Import.cpp.o

include/common/runtime/Import.i: include/common/runtime/Import.cpp.i

.PHONY : include/common/runtime/Import.i

# target to preprocess a source file
include/common/runtime/Import.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Import.cpp.i
.PHONY : include/common/runtime/Import.cpp.i

include/common/runtime/Import.s: include/common/runtime/Import.cpp.s

.PHONY : include/common/runtime/Import.s

# target to generate assembly for a file
include/common/runtime/Import.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Import.cpp.s
.PHONY : include/common/runtime/Import.cpp.s

include/common/runtime/MemoryPool.o: include/common/runtime/MemoryPool.cpp.o

.PHONY : include/common/runtime/MemoryPool.o

# target to build an object file
include/common/runtime/MemoryPool.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/MemoryPool.cpp.o
.PHONY : include/common/runtime/MemoryPool.cpp.o

include/common/runtime/MemoryPool.i: include/common/runtime/MemoryPool.cpp.i

.PHONY : include/common/runtime/MemoryPool.i

# target to preprocess a source file
include/common/runtime/MemoryPool.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/MemoryPool.cpp.i
.PHONY : include/common/runtime/MemoryPool.cpp.i

include/common/runtime/MemoryPool.s: include/common/runtime/MemoryPool.cpp.s

.PHONY : include/common/runtime/MemoryPool.s

# target to generate assembly for a file
include/common/runtime/MemoryPool.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/MemoryPool.cpp.s
.PHONY : include/common/runtime/MemoryPool.cpp.s

include/common/runtime/Profile.o: include/common/runtime/Profile.cpp.o

.PHONY : include/common/runtime/Profile.o

# target to build an object file
include/common/runtime/Profile.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Profile.cpp.o
.PHONY : include/common/runtime/Profile.cpp.o

include/common/runtime/Profile.i: include/common/runtime/Profile.cpp.i

.PHONY : include/common/runtime/Profile.i

# target to preprocess a source file
include/common/runtime/Profile.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Profile.cpp.i
.PHONY : include/common/runtime/Profile.cpp.i

include/common/runtime/Profile.s: include/common/runtime/Profile.cpp.s

.PHONY : include/common/runtime/Profile.s

# target to generate assembly for a file
include/common/runtime/Profile.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Profile.cpp.s
.PHONY : include/common/runtime/Profile.cpp.s

include/common/runtime/String.o: include/common/runtime/String.cpp.o

.PHONY : include/common/runtime/String.o

# target to build an object file
include/common/runtime/String.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/String.cpp.o
.PHONY : include/common/runtime/String.cpp.o

include/common/runtime/String.i: include/common/runtime/String.cpp.i

.PHONY : include/common/runtime/String.i

# target to preprocess a source file
include/common/runtime/String.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/String.cpp.i
.PHONY : include/common/runtime/String.cpp.i

include/common/runtime/String.s: include/common/runtime/String.cpp.s

.PHONY : include/common/runtime/String.s

# target to generate assembly for a file
include/common/runtime/String.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/String.cpp.s
.PHONY : include/common/runtime/String.cpp.s

include/common/runtime/Types.o: include/common/runtime/Types.cpp.o

.PHONY : include/common/runtime/Types.o

# target to build an object file
include/common/runtime/Types.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Types.cpp.o
.PHONY : include/common/runtime/Types.cpp.o

include/common/runtime/Types.i: include/common/runtime/Types.cpp.i

.PHONY : include/common/runtime/Types.i

# target to preprocess a source file
include/common/runtime/Types.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Types.cpp.i
.PHONY : include/common/runtime/Types.cpp.i

include/common/runtime/Types.s: include/common/runtime/Types.cpp.s

.PHONY : include/common/runtime/Types.s

# target to generate assembly for a file
include/common/runtime/Types.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/include/common/runtime/Types.cpp.s
.PHONY : include/common/runtime/Types.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/openCLDispatcher.dir/build.make CMakeFiles/openCLDispatcher.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... openCLDispatcher"
	@echo "... edit_cache"
	@echo "... include/common/algebra/Operators.o"
	@echo "... include/common/algebra/Operators.i"
	@echo "... include/common/algebra/Operators.s"
	@echo "... include/common/algebra/Pipeline.o"
	@echo "... include/common/algebra/Pipeline.i"
	@echo "... include/common/algebra/Pipeline.s"
	@echo "... include/common/algebra/Types.o"
	@echo "... include/common/algebra/Types.i"
	@echo "... include/common/algebra/Types.s"
	@echo "... include/common/runtime/Concurrency.o"
	@echo "... include/common/runtime/Concurrency.i"
	@echo "... include/common/runtime/Concurrency.s"
	@echo "... include/common/runtime/Database.o"
	@echo "... include/common/runtime/Database.i"
	@echo "... include/common/runtime/Database.s"
	@echo "... include/common/runtime/Hashmap.o"
	@echo "... include/common/runtime/Hashmap.i"
	@echo "... include/common/runtime/Hashmap.s"
	@echo "... include/common/runtime/Import.o"
	@echo "... include/common/runtime/Import.i"
	@echo "... include/common/runtime/Import.s"
	@echo "... include/common/runtime/MemoryPool.o"
	@echo "... include/common/runtime/MemoryPool.i"
	@echo "... include/common/runtime/MemoryPool.s"
	@echo "... include/common/runtime/Profile.o"
	@echo "... include/common/runtime/Profile.i"
	@echo "... include/common/runtime/Profile.s"
	@echo "... include/common/runtime/String.o"
	@echo "... include/common/runtime/String.i"
	@echo "... include/common/runtime/String.s"
	@echo "... include/common/runtime/Types.o"
	@echo "... include/common/runtime/Types.i"
	@echo "... include/common/runtime/Types.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

