# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gurumurt/Phd/HeroDB/SQL_flow/db-engine-paradigms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gurumurt/Phd/HeroDB/SQL_flow/db-engine-paradigms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/gurumurt/clion-2017.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gurumurt/Phd/HeroDB/SQL_flow/db-engine-paradigms/CMakeFiles /home/gurumurt/Phd/HeroDB/SQL_flow/db-engine-paradigms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gurumurt/Phd/HeroDB/SQL_flow/db-engine-paradigms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_all

# Build rule for target.
test_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all
.PHONY : test_all

# fast build rule for target.
test_all/fast:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/build
.PHONY : test_all/fast

#=============================================================================
# Target rules for targets named tpch

# Build rule for target.
tpch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tpch
.PHONY : tpch

# fast build rule for target.
tpch/fast:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/build
.PHONY : tpch/fast

#=============================================================================
# Target rules for targets named run_tpch

# Build rule for target.
run_tpch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tpch
.PHONY : run_tpch

# fast build rule for target.
run_tpch/fast:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/build
.PHONY : run_tpch/fast

#=============================================================================
# Target rules for targets named vectorwise

# Build rule for target.
vectorwise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vectorwise
.PHONY : vectorwise

# fast build rule for target.
vectorwise/fast:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/build
.PHONY : vectorwise/fast

#=============================================================================
# Target rules for targets named hyper

# Build rule for target.
hyper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyper
.PHONY : hyper

# fast build rule for target.
hyper/fast:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/build
.PHONY : hyper/fast

#=============================================================================
# Target rules for targets named benchmark_config

# Build rule for target.
benchmark_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark_config
.PHONY : benchmark_config

# fast build rule for target.
benchmark_config/fast:
	$(MAKE) -f CMakeFiles/benchmark_config.dir/build.make CMakeFiles/benchmark_config.dir/build
.PHONY : benchmark_config/fast

#=============================================================================
# Target rules for targets named run_ssb

# Build rule for target.
run_ssb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_ssb
.PHONY : run_ssb

# fast build rule for target.
run_ssb/fast:
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/build
.PHONY : run_ssb/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named run_prim

# Build rule for target.
run_prim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_prim
.PHONY : run_prim

# fast build rule for target.
run_prim/fast:
	$(MAKE) -f CMakeFiles/run_prim.dir/build.make CMakeFiles/run_prim.dir/build
.PHONY : run_prim/fast

#=============================================================================
# Target rules for targets named ssb

# Build rule for target.
ssb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssb
.PHONY : ssb

# fast build rule for target.
ssb/fast:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/build
.PHONY : ssb/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named listevents

# Build rule for target.
listevents: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 listevents
.PHONY : listevents

# fast build rule for target.
listevents/fast:
	$(MAKE) -f 3rdparty/jevents/CMakeFiles/listevents.dir/build.make 3rdparty/jevents/CMakeFiles/listevents.dir/build
.PHONY : listevents/fast

#=============================================================================
# Target rules for targets named jevents

# Build rule for target.
jevents: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jevents
.PHONY : jevents

# fast build rule for target.
jevents/fast:
	$(MAKE) -f 3rdparty/jevents/CMakeFiles/jevents.dir/build.make 3rdparty/jevents/CMakeFiles/jevents.dir/build
.PHONY : jevents/fast

src/bench.o: src/bench.cpp.o

.PHONY : src/bench.o

# target to build an object file
src/bench.cpp.o:
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/bench.cpp.o
.PHONY : src/bench.cpp.o

src/bench.i: src/bench.cpp.i

.PHONY : src/bench.i

# target to preprocess a source file
src/bench.cpp.i:
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/bench.cpp.i
.PHONY : src/bench.cpp.i

src/bench.s: src/bench.cpp.s

.PHONY : src/bench.s

# target to generate assembly for a file
src/bench.cpp.s:
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/bench.cpp.s
.PHONY : src/bench.cpp.s

src/benchmarks/config.o: src/benchmarks/config.cpp.o

.PHONY : src/benchmarks/config.o

# target to build an object file
src/benchmarks/config.cpp.o:
	$(MAKE) -f CMakeFiles/benchmark_config.dir/build.make CMakeFiles/benchmark_config.dir/src/benchmarks/config.cpp.o
.PHONY : src/benchmarks/config.cpp.o

src/benchmarks/config.i: src/benchmarks/config.cpp.i

.PHONY : src/benchmarks/config.i

# target to preprocess a source file
src/benchmarks/config.cpp.i:
	$(MAKE) -f CMakeFiles/benchmark_config.dir/build.make CMakeFiles/benchmark_config.dir/src/benchmarks/config.cpp.i
.PHONY : src/benchmarks/config.cpp.i

src/benchmarks/config.s: src/benchmarks/config.cpp.s

.PHONY : src/benchmarks/config.s

# target to generate assembly for a file
src/benchmarks/config.cpp.s:
	$(MAKE) -f CMakeFiles/benchmark_config.dir/build.make CMakeFiles/benchmark_config.dir/src/benchmarks/config.cpp.s
.PHONY : src/benchmarks/config.cpp.s

src/benchmarks/primitives/run.o: src/benchmarks/primitives/run.cpp.o

.PHONY : src/benchmarks/primitives/run.o

# target to build an object file
src/benchmarks/primitives/run.cpp.o:
	$(MAKE) -f CMakeFiles/run_prim.dir/build.make CMakeFiles/run_prim.dir/src/benchmarks/primitives/run.cpp.o
.PHONY : src/benchmarks/primitives/run.cpp.o

src/benchmarks/primitives/run.i: src/benchmarks/primitives/run.cpp.i

.PHONY : src/benchmarks/primitives/run.i

# target to preprocess a source file
src/benchmarks/primitives/run.cpp.i:
	$(MAKE) -f CMakeFiles/run_prim.dir/build.make CMakeFiles/run_prim.dir/src/benchmarks/primitives/run.cpp.i
.PHONY : src/benchmarks/primitives/run.cpp.i

src/benchmarks/primitives/run.s: src/benchmarks/primitives/run.cpp.s

.PHONY : src/benchmarks/primitives/run.s

# target to generate assembly for a file
src/benchmarks/primitives/run.cpp.s:
	$(MAKE) -f CMakeFiles/run_prim.dir/build.make CMakeFiles/run_prim.dir/src/benchmarks/primitives/run.cpp.s
.PHONY : src/benchmarks/primitives/run.cpp.s

src/benchmarks/sbb/queries/q11.o: src/benchmarks/sbb/queries/q11.cpp.o

.PHONY : src/benchmarks/sbb/queries/q11.o

# target to build an object file
src/benchmarks/sbb/queries/q11.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q11.cpp.o
.PHONY : src/benchmarks/sbb/queries/q11.cpp.o

src/benchmarks/sbb/queries/q11.i: src/benchmarks/sbb/queries/q11.cpp.i

.PHONY : src/benchmarks/sbb/queries/q11.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q11.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q11.cpp.i
.PHONY : src/benchmarks/sbb/queries/q11.cpp.i

src/benchmarks/sbb/queries/q11.s: src/benchmarks/sbb/queries/q11.cpp.s

.PHONY : src/benchmarks/sbb/queries/q11.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q11.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q11.cpp.s
.PHONY : src/benchmarks/sbb/queries/q11.cpp.s

src/benchmarks/sbb/queries/q12.o: src/benchmarks/sbb/queries/q12.cpp.o

.PHONY : src/benchmarks/sbb/queries/q12.o

# target to build an object file
src/benchmarks/sbb/queries/q12.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q12.cpp.o
.PHONY : src/benchmarks/sbb/queries/q12.cpp.o

src/benchmarks/sbb/queries/q12.i: src/benchmarks/sbb/queries/q12.cpp.i

.PHONY : src/benchmarks/sbb/queries/q12.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q12.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q12.cpp.i
.PHONY : src/benchmarks/sbb/queries/q12.cpp.i

src/benchmarks/sbb/queries/q12.s: src/benchmarks/sbb/queries/q12.cpp.s

.PHONY : src/benchmarks/sbb/queries/q12.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q12.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q12.cpp.s
.PHONY : src/benchmarks/sbb/queries/q12.cpp.s

src/benchmarks/sbb/queries/q13.o: src/benchmarks/sbb/queries/q13.cpp.o

.PHONY : src/benchmarks/sbb/queries/q13.o

# target to build an object file
src/benchmarks/sbb/queries/q13.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q13.cpp.o
.PHONY : src/benchmarks/sbb/queries/q13.cpp.o

src/benchmarks/sbb/queries/q13.i: src/benchmarks/sbb/queries/q13.cpp.i

.PHONY : src/benchmarks/sbb/queries/q13.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q13.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q13.cpp.i
.PHONY : src/benchmarks/sbb/queries/q13.cpp.i

src/benchmarks/sbb/queries/q13.s: src/benchmarks/sbb/queries/q13.cpp.s

.PHONY : src/benchmarks/sbb/queries/q13.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q13.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q13.cpp.s
.PHONY : src/benchmarks/sbb/queries/q13.cpp.s

src/benchmarks/sbb/queries/q21.o: src/benchmarks/sbb/queries/q21.cpp.o

.PHONY : src/benchmarks/sbb/queries/q21.o

# target to build an object file
src/benchmarks/sbb/queries/q21.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q21.cpp.o
.PHONY : src/benchmarks/sbb/queries/q21.cpp.o

src/benchmarks/sbb/queries/q21.i: src/benchmarks/sbb/queries/q21.cpp.i

.PHONY : src/benchmarks/sbb/queries/q21.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q21.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q21.cpp.i
.PHONY : src/benchmarks/sbb/queries/q21.cpp.i

src/benchmarks/sbb/queries/q21.s: src/benchmarks/sbb/queries/q21.cpp.s

.PHONY : src/benchmarks/sbb/queries/q21.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q21.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q21.cpp.s
.PHONY : src/benchmarks/sbb/queries/q21.cpp.s

src/benchmarks/sbb/queries/q22.o: src/benchmarks/sbb/queries/q22.cpp.o

.PHONY : src/benchmarks/sbb/queries/q22.o

# target to build an object file
src/benchmarks/sbb/queries/q22.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q22.cpp.o
.PHONY : src/benchmarks/sbb/queries/q22.cpp.o

src/benchmarks/sbb/queries/q22.i: src/benchmarks/sbb/queries/q22.cpp.i

.PHONY : src/benchmarks/sbb/queries/q22.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q22.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q22.cpp.i
.PHONY : src/benchmarks/sbb/queries/q22.cpp.i

src/benchmarks/sbb/queries/q22.s: src/benchmarks/sbb/queries/q22.cpp.s

.PHONY : src/benchmarks/sbb/queries/q22.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q22.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q22.cpp.s
.PHONY : src/benchmarks/sbb/queries/q22.cpp.s

src/benchmarks/sbb/queries/q23.o: src/benchmarks/sbb/queries/q23.cpp.o

.PHONY : src/benchmarks/sbb/queries/q23.o

# target to build an object file
src/benchmarks/sbb/queries/q23.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q23.cpp.o
.PHONY : src/benchmarks/sbb/queries/q23.cpp.o

src/benchmarks/sbb/queries/q23.i: src/benchmarks/sbb/queries/q23.cpp.i

.PHONY : src/benchmarks/sbb/queries/q23.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q23.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q23.cpp.i
.PHONY : src/benchmarks/sbb/queries/q23.cpp.i

src/benchmarks/sbb/queries/q23.s: src/benchmarks/sbb/queries/q23.cpp.s

.PHONY : src/benchmarks/sbb/queries/q23.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q23.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q23.cpp.s
.PHONY : src/benchmarks/sbb/queries/q23.cpp.s

src/benchmarks/sbb/queries/q31.o: src/benchmarks/sbb/queries/q31.cpp.o

.PHONY : src/benchmarks/sbb/queries/q31.o

# target to build an object file
src/benchmarks/sbb/queries/q31.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q31.cpp.o
.PHONY : src/benchmarks/sbb/queries/q31.cpp.o

src/benchmarks/sbb/queries/q31.i: src/benchmarks/sbb/queries/q31.cpp.i

.PHONY : src/benchmarks/sbb/queries/q31.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q31.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q31.cpp.i
.PHONY : src/benchmarks/sbb/queries/q31.cpp.i

src/benchmarks/sbb/queries/q31.s: src/benchmarks/sbb/queries/q31.cpp.s

.PHONY : src/benchmarks/sbb/queries/q31.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q31.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q31.cpp.s
.PHONY : src/benchmarks/sbb/queries/q31.cpp.s

src/benchmarks/sbb/queries/q32.o: src/benchmarks/sbb/queries/q32.cpp.o

.PHONY : src/benchmarks/sbb/queries/q32.o

# target to build an object file
src/benchmarks/sbb/queries/q32.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q32.cpp.o
.PHONY : src/benchmarks/sbb/queries/q32.cpp.o

src/benchmarks/sbb/queries/q32.i: src/benchmarks/sbb/queries/q32.cpp.i

.PHONY : src/benchmarks/sbb/queries/q32.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q32.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q32.cpp.i
.PHONY : src/benchmarks/sbb/queries/q32.cpp.i

src/benchmarks/sbb/queries/q32.s: src/benchmarks/sbb/queries/q32.cpp.s

.PHONY : src/benchmarks/sbb/queries/q32.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q32.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q32.cpp.s
.PHONY : src/benchmarks/sbb/queries/q32.cpp.s

src/benchmarks/sbb/queries/q33.o: src/benchmarks/sbb/queries/q33.cpp.o

.PHONY : src/benchmarks/sbb/queries/q33.o

# target to build an object file
src/benchmarks/sbb/queries/q33.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q33.cpp.o
.PHONY : src/benchmarks/sbb/queries/q33.cpp.o

src/benchmarks/sbb/queries/q33.i: src/benchmarks/sbb/queries/q33.cpp.i

.PHONY : src/benchmarks/sbb/queries/q33.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q33.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q33.cpp.i
.PHONY : src/benchmarks/sbb/queries/q33.cpp.i

src/benchmarks/sbb/queries/q33.s: src/benchmarks/sbb/queries/q33.cpp.s

.PHONY : src/benchmarks/sbb/queries/q33.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q33.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q33.cpp.s
.PHONY : src/benchmarks/sbb/queries/q33.cpp.s

src/benchmarks/sbb/queries/q34.o: src/benchmarks/sbb/queries/q34.cpp.o

.PHONY : src/benchmarks/sbb/queries/q34.o

# target to build an object file
src/benchmarks/sbb/queries/q34.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q34.cpp.o
.PHONY : src/benchmarks/sbb/queries/q34.cpp.o

src/benchmarks/sbb/queries/q34.i: src/benchmarks/sbb/queries/q34.cpp.i

.PHONY : src/benchmarks/sbb/queries/q34.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q34.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q34.cpp.i
.PHONY : src/benchmarks/sbb/queries/q34.cpp.i

src/benchmarks/sbb/queries/q34.s: src/benchmarks/sbb/queries/q34.cpp.s

.PHONY : src/benchmarks/sbb/queries/q34.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q34.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q34.cpp.s
.PHONY : src/benchmarks/sbb/queries/q34.cpp.s

src/benchmarks/sbb/queries/q41.o: src/benchmarks/sbb/queries/q41.cpp.o

.PHONY : src/benchmarks/sbb/queries/q41.o

# target to build an object file
src/benchmarks/sbb/queries/q41.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q41.cpp.o
.PHONY : src/benchmarks/sbb/queries/q41.cpp.o

src/benchmarks/sbb/queries/q41.i: src/benchmarks/sbb/queries/q41.cpp.i

.PHONY : src/benchmarks/sbb/queries/q41.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q41.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q41.cpp.i
.PHONY : src/benchmarks/sbb/queries/q41.cpp.i

src/benchmarks/sbb/queries/q41.s: src/benchmarks/sbb/queries/q41.cpp.s

.PHONY : src/benchmarks/sbb/queries/q41.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q41.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q41.cpp.s
.PHONY : src/benchmarks/sbb/queries/q41.cpp.s

src/benchmarks/sbb/queries/q42.o: src/benchmarks/sbb/queries/q42.cpp.o

.PHONY : src/benchmarks/sbb/queries/q42.o

# target to build an object file
src/benchmarks/sbb/queries/q42.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q42.cpp.o
.PHONY : src/benchmarks/sbb/queries/q42.cpp.o

src/benchmarks/sbb/queries/q42.i: src/benchmarks/sbb/queries/q42.cpp.i

.PHONY : src/benchmarks/sbb/queries/q42.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q42.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q42.cpp.i
.PHONY : src/benchmarks/sbb/queries/q42.cpp.i

src/benchmarks/sbb/queries/q42.s: src/benchmarks/sbb/queries/q42.cpp.s

.PHONY : src/benchmarks/sbb/queries/q42.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q42.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q42.cpp.s
.PHONY : src/benchmarks/sbb/queries/q42.cpp.s

src/benchmarks/sbb/queries/q43.o: src/benchmarks/sbb/queries/q43.cpp.o

.PHONY : src/benchmarks/sbb/queries/q43.o

# target to build an object file
src/benchmarks/sbb/queries/q43.cpp.o:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q43.cpp.o
.PHONY : src/benchmarks/sbb/queries/q43.cpp.o

src/benchmarks/sbb/queries/q43.i: src/benchmarks/sbb/queries/q43.cpp.i

.PHONY : src/benchmarks/sbb/queries/q43.i

# target to preprocess a source file
src/benchmarks/sbb/queries/q43.cpp.i:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q43.cpp.i
.PHONY : src/benchmarks/sbb/queries/q43.cpp.i

src/benchmarks/sbb/queries/q43.s: src/benchmarks/sbb/queries/q43.cpp.s

.PHONY : src/benchmarks/sbb/queries/q43.s

# target to generate assembly for a file
src/benchmarks/sbb/queries/q43.cpp.s:
	$(MAKE) -f CMakeFiles/ssb.dir/build.make CMakeFiles/ssb.dir/src/benchmarks/sbb/queries/q43.cpp.s
.PHONY : src/benchmarks/sbb/queries/q43.cpp.s

src/benchmarks/sbb/run.o: src/benchmarks/sbb/run.cpp.o

.PHONY : src/benchmarks/sbb/run.o

# target to build an object file
src/benchmarks/sbb/run.cpp.o:
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/benchmarks/sbb/run.cpp.o
.PHONY : src/benchmarks/sbb/run.cpp.o

src/benchmarks/sbb/run.i: src/benchmarks/sbb/run.cpp.i

.PHONY : src/benchmarks/sbb/run.i

# target to preprocess a source file
src/benchmarks/sbb/run.cpp.i:
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/benchmarks/sbb/run.cpp.i
.PHONY : src/benchmarks/sbb/run.cpp.i

src/benchmarks/sbb/run.s: src/benchmarks/sbb/run.cpp.s

.PHONY : src/benchmarks/sbb/run.s

# target to generate assembly for a file
src/benchmarks/sbb/run.cpp.s:
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/benchmarks/sbb/run.cpp.s
.PHONY : src/benchmarks/sbb/run.cpp.s

src/benchmarks/tpch/queries/q1.o: src/benchmarks/tpch/queries/q1.cpp.o

.PHONY : src/benchmarks/tpch/queries/q1.o

# target to build an object file
src/benchmarks/tpch/queries/q1.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q1.cpp.o
.PHONY : src/benchmarks/tpch/queries/q1.cpp.o

src/benchmarks/tpch/queries/q1.i: src/benchmarks/tpch/queries/q1.cpp.i

.PHONY : src/benchmarks/tpch/queries/q1.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q1.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q1.cpp.i
.PHONY : src/benchmarks/tpch/queries/q1.cpp.i

src/benchmarks/tpch/queries/q1.s: src/benchmarks/tpch/queries/q1.cpp.s

.PHONY : src/benchmarks/tpch/queries/q1.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q1.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q1.cpp.s
.PHONY : src/benchmarks/tpch/queries/q1.cpp.s

src/benchmarks/tpch/queries/q18.o: src/benchmarks/tpch/queries/q18.cpp.o

.PHONY : src/benchmarks/tpch/queries/q18.o

# target to build an object file
src/benchmarks/tpch/queries/q18.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q18.cpp.o
.PHONY : src/benchmarks/tpch/queries/q18.cpp.o

src/benchmarks/tpch/queries/q18.i: src/benchmarks/tpch/queries/q18.cpp.i

.PHONY : src/benchmarks/tpch/queries/q18.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q18.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q18.cpp.i
.PHONY : src/benchmarks/tpch/queries/q18.cpp.i

src/benchmarks/tpch/queries/q18.s: src/benchmarks/tpch/queries/q18.cpp.s

.PHONY : src/benchmarks/tpch/queries/q18.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q18.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q18.cpp.s
.PHONY : src/benchmarks/tpch/queries/q18.cpp.s

src/benchmarks/tpch/queries/q3.o: src/benchmarks/tpch/queries/q3.cpp.o

.PHONY : src/benchmarks/tpch/queries/q3.o

# target to build an object file
src/benchmarks/tpch/queries/q3.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q3.cpp.o
.PHONY : src/benchmarks/tpch/queries/q3.cpp.o

src/benchmarks/tpch/queries/q3.i: src/benchmarks/tpch/queries/q3.cpp.i

.PHONY : src/benchmarks/tpch/queries/q3.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q3.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q3.cpp.i
.PHONY : src/benchmarks/tpch/queries/q3.cpp.i

src/benchmarks/tpch/queries/q3.s: src/benchmarks/tpch/queries/q3.cpp.s

.PHONY : src/benchmarks/tpch/queries/q3.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q3.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q3.cpp.s
.PHONY : src/benchmarks/tpch/queries/q3.cpp.s

src/benchmarks/tpch/queries/q5.o: src/benchmarks/tpch/queries/q5.cpp.o

.PHONY : src/benchmarks/tpch/queries/q5.o

# target to build an object file
src/benchmarks/tpch/queries/q5.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q5.cpp.o
.PHONY : src/benchmarks/tpch/queries/q5.cpp.o

src/benchmarks/tpch/queries/q5.i: src/benchmarks/tpch/queries/q5.cpp.i

.PHONY : src/benchmarks/tpch/queries/q5.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q5.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q5.cpp.i
.PHONY : src/benchmarks/tpch/queries/q5.cpp.i

src/benchmarks/tpch/queries/q5.s: src/benchmarks/tpch/queries/q5.cpp.s

.PHONY : src/benchmarks/tpch/queries/q5.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q5.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q5.cpp.s
.PHONY : src/benchmarks/tpch/queries/q5.cpp.s

src/benchmarks/tpch/queries/q5_no_sel.o: src/benchmarks/tpch/queries/q5_no_sel.cpp.o

.PHONY : src/benchmarks/tpch/queries/q5_no_sel.o

# target to build an object file
src/benchmarks/tpch/queries/q5_no_sel.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q5_no_sel.cpp.o
.PHONY : src/benchmarks/tpch/queries/q5_no_sel.cpp.o

src/benchmarks/tpch/queries/q5_no_sel.i: src/benchmarks/tpch/queries/q5_no_sel.cpp.i

.PHONY : src/benchmarks/tpch/queries/q5_no_sel.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q5_no_sel.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q5_no_sel.cpp.i
.PHONY : src/benchmarks/tpch/queries/q5_no_sel.cpp.i

src/benchmarks/tpch/queries/q5_no_sel.s: src/benchmarks/tpch/queries/q5_no_sel.cpp.s

.PHONY : src/benchmarks/tpch/queries/q5_no_sel.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q5_no_sel.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q5_no_sel.cpp.s
.PHONY : src/benchmarks/tpch/queries/q5_no_sel.cpp.s

src/benchmarks/tpch/queries/q6.o: src/benchmarks/tpch/queries/q6.cpp.o

.PHONY : src/benchmarks/tpch/queries/q6.o

# target to build an object file
src/benchmarks/tpch/queries/q6.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q6.cpp.o
.PHONY : src/benchmarks/tpch/queries/q6.cpp.o

src/benchmarks/tpch/queries/q6.i: src/benchmarks/tpch/queries/q6.cpp.i

.PHONY : src/benchmarks/tpch/queries/q6.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q6.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q6.cpp.i
.PHONY : src/benchmarks/tpch/queries/q6.cpp.i

src/benchmarks/tpch/queries/q6.s: src/benchmarks/tpch/queries/q6.cpp.s

.PHONY : src/benchmarks/tpch/queries/q6.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q6.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q6.cpp.s
.PHONY : src/benchmarks/tpch/queries/q6.cpp.s

src/benchmarks/tpch/queries/q9.o: src/benchmarks/tpch/queries/q9.cpp.o

.PHONY : src/benchmarks/tpch/queries/q9.o

# target to build an object file
src/benchmarks/tpch/queries/q9.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q9.cpp.o
.PHONY : src/benchmarks/tpch/queries/q9.cpp.o

src/benchmarks/tpch/queries/q9.i: src/benchmarks/tpch/queries/q9.cpp.i

.PHONY : src/benchmarks/tpch/queries/q9.i

# target to preprocess a source file
src/benchmarks/tpch/queries/q9.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q9.cpp.i
.PHONY : src/benchmarks/tpch/queries/q9.cpp.i

src/benchmarks/tpch/queries/q9.s: src/benchmarks/tpch/queries/q9.cpp.s

.PHONY : src/benchmarks/tpch/queries/q9.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/q9.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/q9.cpp.s
.PHONY : src/benchmarks/tpch/queries/q9.cpp.s

src/benchmarks/tpch/queries/qSimple.o: src/benchmarks/tpch/queries/qSimple.cpp.o

.PHONY : src/benchmarks/tpch/queries/qSimple.o

# target to build an object file
src/benchmarks/tpch/queries/qSimple.cpp.o:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/qSimple.cpp.o
.PHONY : src/benchmarks/tpch/queries/qSimple.cpp.o

src/benchmarks/tpch/queries/qSimple.i: src/benchmarks/tpch/queries/qSimple.cpp.i

.PHONY : src/benchmarks/tpch/queries/qSimple.i

# target to preprocess a source file
src/benchmarks/tpch/queries/qSimple.cpp.i:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/qSimple.cpp.i
.PHONY : src/benchmarks/tpch/queries/qSimple.cpp.i

src/benchmarks/tpch/queries/qSimple.s: src/benchmarks/tpch/queries/qSimple.cpp.s

.PHONY : src/benchmarks/tpch/queries/qSimple.s

# target to generate assembly for a file
src/benchmarks/tpch/queries/qSimple.cpp.s:
	$(MAKE) -f CMakeFiles/tpch.dir/build.make CMakeFiles/tpch.dir/src/benchmarks/tpch/queries/qSimple.cpp.s
.PHONY : src/benchmarks/tpch/queries/qSimple.cpp.s

src/benchmarks/tpch/run.o: src/benchmarks/tpch/run.cpp.o

.PHONY : src/benchmarks/tpch/run.o

# target to build an object file
src/benchmarks/tpch/run.cpp.o:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/benchmarks/tpch/run.cpp.o
.PHONY : src/benchmarks/tpch/run.cpp.o

src/benchmarks/tpch/run.i: src/benchmarks/tpch/run.cpp.i

.PHONY : src/benchmarks/tpch/run.i

# target to preprocess a source file
src/benchmarks/tpch/run.cpp.i:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/benchmarks/tpch/run.cpp.i
.PHONY : src/benchmarks/tpch/run.cpp.i

src/benchmarks/tpch/run.s: src/benchmarks/tpch/run.cpp.s

.PHONY : src/benchmarks/tpch/run.s

# target to generate assembly for a file
src/benchmarks/tpch/run.cpp.s:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/benchmarks/tpch/run.cpp.s
.PHONY : src/benchmarks/tpch/run.cpp.s

src/common/algebra/Operators.o: src/common/algebra/Operators.cpp.o

.PHONY : src/common/algebra/Operators.o

# target to build an object file
src/common/algebra/Operators.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/algebra/Operators.cpp.o
.PHONY : src/common/algebra/Operators.cpp.o

src/common/algebra/Operators.i: src/common/algebra/Operators.cpp.i

.PHONY : src/common/algebra/Operators.i

# target to preprocess a source file
src/common/algebra/Operators.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/algebra/Operators.cpp.i
.PHONY : src/common/algebra/Operators.cpp.i

src/common/algebra/Operators.s: src/common/algebra/Operators.cpp.s

.PHONY : src/common/algebra/Operators.s

# target to generate assembly for a file
src/common/algebra/Operators.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/algebra/Operators.cpp.s
.PHONY : src/common/algebra/Operators.cpp.s

src/common/algebra/Types.o: src/common/algebra/Types.cpp.o

.PHONY : src/common/algebra/Types.o

# target to build an object file
src/common/algebra/Types.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/algebra/Types.cpp.o
.PHONY : src/common/algebra/Types.cpp.o

src/common/algebra/Types.i: src/common/algebra/Types.cpp.i

.PHONY : src/common/algebra/Types.i

# target to preprocess a source file
src/common/algebra/Types.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/algebra/Types.cpp.i
.PHONY : src/common/algebra/Types.cpp.i

src/common/algebra/Types.s: src/common/algebra/Types.cpp.s

.PHONY : src/common/algebra/Types.s

# target to generate assembly for a file
src/common/algebra/Types.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/algebra/Types.cpp.s
.PHONY : src/common/algebra/Types.cpp.s

src/common/runtime/Concurrency.o: src/common/runtime/Concurrency.cpp.o

.PHONY : src/common/runtime/Concurrency.o

# target to build an object file
src/common/runtime/Concurrency.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Concurrency.cpp.o
.PHONY : src/common/runtime/Concurrency.cpp.o

src/common/runtime/Concurrency.i: src/common/runtime/Concurrency.cpp.i

.PHONY : src/common/runtime/Concurrency.i

# target to preprocess a source file
src/common/runtime/Concurrency.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Concurrency.cpp.i
.PHONY : src/common/runtime/Concurrency.cpp.i

src/common/runtime/Concurrency.s: src/common/runtime/Concurrency.cpp.s

.PHONY : src/common/runtime/Concurrency.s

# target to generate assembly for a file
src/common/runtime/Concurrency.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Concurrency.cpp.s
.PHONY : src/common/runtime/Concurrency.cpp.s

src/common/runtime/Database.o: src/common/runtime/Database.cpp.o

.PHONY : src/common/runtime/Database.o

# target to build an object file
src/common/runtime/Database.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Database.cpp.o
.PHONY : src/common/runtime/Database.cpp.o

src/common/runtime/Database.i: src/common/runtime/Database.cpp.i

.PHONY : src/common/runtime/Database.i

# target to preprocess a source file
src/common/runtime/Database.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Database.cpp.i
.PHONY : src/common/runtime/Database.cpp.i

src/common/runtime/Database.s: src/common/runtime/Database.cpp.s

.PHONY : src/common/runtime/Database.s

# target to generate assembly for a file
src/common/runtime/Database.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Database.cpp.s
.PHONY : src/common/runtime/Database.cpp.s

src/common/runtime/Hashmap.o: src/common/runtime/Hashmap.cpp.o

.PHONY : src/common/runtime/Hashmap.o

# target to build an object file
src/common/runtime/Hashmap.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Hashmap.cpp.o
.PHONY : src/common/runtime/Hashmap.cpp.o

src/common/runtime/Hashmap.i: src/common/runtime/Hashmap.cpp.i

.PHONY : src/common/runtime/Hashmap.i

# target to preprocess a source file
src/common/runtime/Hashmap.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Hashmap.cpp.i
.PHONY : src/common/runtime/Hashmap.cpp.i

src/common/runtime/Hashmap.s: src/common/runtime/Hashmap.cpp.s

.PHONY : src/common/runtime/Hashmap.s

# target to generate assembly for a file
src/common/runtime/Hashmap.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Hashmap.cpp.s
.PHONY : src/common/runtime/Hashmap.cpp.s

src/common/runtime/Import.o: src/common/runtime/Import.cpp.o

.PHONY : src/common/runtime/Import.o

# target to build an object file
src/common/runtime/Import.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Import.cpp.o
.PHONY : src/common/runtime/Import.cpp.o

src/common/runtime/Import.i: src/common/runtime/Import.cpp.i

.PHONY : src/common/runtime/Import.i

# target to preprocess a source file
src/common/runtime/Import.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Import.cpp.i
.PHONY : src/common/runtime/Import.cpp.i

src/common/runtime/Import.s: src/common/runtime/Import.cpp.s

.PHONY : src/common/runtime/Import.s

# target to generate assembly for a file
src/common/runtime/Import.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Import.cpp.s
.PHONY : src/common/runtime/Import.cpp.s

src/common/runtime/MemoryPool.o: src/common/runtime/MemoryPool.cpp.o

.PHONY : src/common/runtime/MemoryPool.o

# target to build an object file
src/common/runtime/MemoryPool.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/MemoryPool.cpp.o
.PHONY : src/common/runtime/MemoryPool.cpp.o

src/common/runtime/MemoryPool.i: src/common/runtime/MemoryPool.cpp.i

.PHONY : src/common/runtime/MemoryPool.i

# target to preprocess a source file
src/common/runtime/MemoryPool.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/MemoryPool.cpp.i
.PHONY : src/common/runtime/MemoryPool.cpp.i

src/common/runtime/MemoryPool.s: src/common/runtime/MemoryPool.cpp.s

.PHONY : src/common/runtime/MemoryPool.s

# target to generate assembly for a file
src/common/runtime/MemoryPool.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/MemoryPool.cpp.s
.PHONY : src/common/runtime/MemoryPool.cpp.s

src/common/runtime/Profile.o: src/common/runtime/Profile.cpp.o

.PHONY : src/common/runtime/Profile.o

# target to build an object file
src/common/runtime/Profile.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Profile.cpp.o
.PHONY : src/common/runtime/Profile.cpp.o

src/common/runtime/Profile.i: src/common/runtime/Profile.cpp.i

.PHONY : src/common/runtime/Profile.i

# target to preprocess a source file
src/common/runtime/Profile.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Profile.cpp.i
.PHONY : src/common/runtime/Profile.cpp.i

src/common/runtime/Profile.s: src/common/runtime/Profile.cpp.s

.PHONY : src/common/runtime/Profile.s

# target to generate assembly for a file
src/common/runtime/Profile.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Profile.cpp.s
.PHONY : src/common/runtime/Profile.cpp.s

src/common/runtime/String.o: src/common/runtime/String.cpp.o

.PHONY : src/common/runtime/String.o

# target to build an object file
src/common/runtime/String.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/String.cpp.o
.PHONY : src/common/runtime/String.cpp.o

src/common/runtime/String.i: src/common/runtime/String.cpp.i

.PHONY : src/common/runtime/String.i

# target to preprocess a source file
src/common/runtime/String.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/String.cpp.i
.PHONY : src/common/runtime/String.cpp.i

src/common/runtime/String.s: src/common/runtime/String.cpp.s

.PHONY : src/common/runtime/String.s

# target to generate assembly for a file
src/common/runtime/String.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/String.cpp.s
.PHONY : src/common/runtime/String.cpp.s

src/common/runtime/Types.o: src/common/runtime/Types.cpp.o

.PHONY : src/common/runtime/Types.o

# target to build an object file
src/common/runtime/Types.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Types.cpp.o
.PHONY : src/common/runtime/Types.cpp.o

src/common/runtime/Types.i: src/common/runtime/Types.cpp.i

.PHONY : src/common/runtime/Types.i

# target to preprocess a source file
src/common/runtime/Types.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Types.cpp.i
.PHONY : src/common/runtime/Types.cpp.i

src/common/runtime/Types.s: src/common/runtime/Types.cpp.s

.PHONY : src/common/runtime/Types.s

# target to generate assembly for a file
src/common/runtime/Types.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/runtime/Types.cpp.s
.PHONY : src/common/runtime/Types.cpp.s

src/hyper/codegen/Translator.o: src/hyper/codegen/Translator.cpp.o

.PHONY : src/hyper/codegen/Translator.o

# target to build an object file
src/hyper/codegen/Translator.cpp.o:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/hyper/codegen/Translator.cpp.o
.PHONY : src/hyper/codegen/Translator.cpp.o

src/hyper/codegen/Translator.i: src/hyper/codegen/Translator.cpp.i

.PHONY : src/hyper/codegen/Translator.i

# target to preprocess a source file
src/hyper/codegen/Translator.cpp.i:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/hyper/codegen/Translator.cpp.i
.PHONY : src/hyper/codegen/Translator.cpp.i

src/hyper/codegen/Translator.s: src/hyper/codegen/Translator.cpp.s

.PHONY : src/hyper/codegen/Translator.s

# target to generate assembly for a file
src/hyper/codegen/Translator.cpp.s:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/hyper/codegen/Translator.cpp.s
.PHONY : src/hyper/codegen/Translator.cpp.s

src/hyper/codegen/TranslatorRegistry.o: src/hyper/codegen/TranslatorRegistry.cpp.o

.PHONY : src/hyper/codegen/TranslatorRegistry.o

# target to build an object file
src/hyper/codegen/TranslatorRegistry.cpp.o:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/hyper/codegen/TranslatorRegistry.cpp.o
.PHONY : src/hyper/codegen/TranslatorRegistry.cpp.o

src/hyper/codegen/TranslatorRegistry.i: src/hyper/codegen/TranslatorRegistry.cpp.i

.PHONY : src/hyper/codegen/TranslatorRegistry.i

# target to preprocess a source file
src/hyper/codegen/TranslatorRegistry.cpp.i:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/hyper/codegen/TranslatorRegistry.cpp.i
.PHONY : src/hyper/codegen/TranslatorRegistry.cpp.i

src/hyper/codegen/TranslatorRegistry.s: src/hyper/codegen/TranslatorRegistry.cpp.s

.PHONY : src/hyper/codegen/TranslatorRegistry.s

# target to generate assembly for a file
src/hyper/codegen/TranslatorRegistry.cpp.s:
	$(MAKE) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/hyper/codegen/TranslatorRegistry.cpp.s
.PHONY : src/hyper/codegen/TranslatorRegistry.cpp.s

src/hyper/codegen/operators/Map.o: src/hyper/codegen/operators/Map.cpp.o

.PHONY : src/hyper/codegen/operators/Map.o

# target to build an object file
src/hyper/codegen/operators/Map.cpp.o:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Map.cpp.o
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Map.cpp.o
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Map.cpp.o
.PHONY : src/hyper/codegen/operators/Map.cpp.o

src/hyper/codegen/operators/Map.i: src/hyper/codegen/operators/Map.cpp.i

.PHONY : src/hyper/codegen/operators/Map.i

# target to preprocess a source file
src/hyper/codegen/operators/Map.cpp.i:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Map.cpp.i
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Map.cpp.i
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Map.cpp.i
.PHONY : src/hyper/codegen/operators/Map.cpp.i

src/hyper/codegen/operators/Map.s: src/hyper/codegen/operators/Map.cpp.s

.PHONY : src/hyper/codegen/operators/Map.s

# target to generate assembly for a file
src/hyper/codegen/operators/Map.cpp.s:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Map.cpp.s
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Map.cpp.s
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Map.cpp.s
.PHONY : src/hyper/codegen/operators/Map.cpp.s

src/hyper/codegen/operators/Print.o: src/hyper/codegen/operators/Print.cpp.o

.PHONY : src/hyper/codegen/operators/Print.o

# target to build an object file
src/hyper/codegen/operators/Print.cpp.o:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Print.cpp.o
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Print.cpp.o
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Print.cpp.o
.PHONY : src/hyper/codegen/operators/Print.cpp.o

src/hyper/codegen/operators/Print.i: src/hyper/codegen/operators/Print.cpp.i

.PHONY : src/hyper/codegen/operators/Print.i

# target to preprocess a source file
src/hyper/codegen/operators/Print.cpp.i:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Print.cpp.i
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Print.cpp.i
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Print.cpp.i
.PHONY : src/hyper/codegen/operators/Print.cpp.i

src/hyper/codegen/operators/Print.s: src/hyper/codegen/operators/Print.cpp.s

.PHONY : src/hyper/codegen/operators/Print.s

# target to generate assembly for a file
src/hyper/codegen/operators/Print.cpp.s:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Print.cpp.s
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Print.cpp.s
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Print.cpp.s
.PHONY : src/hyper/codegen/operators/Print.cpp.s

src/hyper/codegen/operators/Scan.o: src/hyper/codegen/operators/Scan.cpp.o

.PHONY : src/hyper/codegen/operators/Scan.o

# target to build an object file
src/hyper/codegen/operators/Scan.cpp.o:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Scan.cpp.o
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Scan.cpp.o
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Scan.cpp.o
.PHONY : src/hyper/codegen/operators/Scan.cpp.o

src/hyper/codegen/operators/Scan.i: src/hyper/codegen/operators/Scan.cpp.i

.PHONY : src/hyper/codegen/operators/Scan.i

# target to preprocess a source file
src/hyper/codegen/operators/Scan.cpp.i:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Scan.cpp.i
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Scan.cpp.i
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Scan.cpp.i
.PHONY : src/hyper/codegen/operators/Scan.cpp.i

src/hyper/codegen/operators/Scan.s: src/hyper/codegen/operators/Scan.cpp.s

.PHONY : src/hyper/codegen/operators/Scan.s

# target to generate assembly for a file
src/hyper/codegen/operators/Scan.cpp.s:
	$(MAKE) -f CMakeFiles/run_tpch.dir/build.make CMakeFiles/run_tpch.dir/src/hyper/codegen/operators/Scan.cpp.s
	$(MAKE) -f CMakeFiles/run_ssb.dir/build.make CMakeFiles/run_ssb.dir/src/hyper/codegen/operators/Scan.cpp.s
	$(MAKE) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/src/hyper/codegen/operators/Scan.cpp.s
.PHONY : src/hyper/codegen/operators/Scan.cpp.s

src/test/common/Database.o: src/test/common/Database.cpp.o

.PHONY : src/test/common/Database.o

# target to build an object file
src/test/common/Database.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Database.cpp.o
.PHONY : src/test/common/Database.cpp.o

src/test/common/Database.i: src/test/common/Database.cpp.i

.PHONY : src/test/common/Database.i

# target to preprocess a source file
src/test/common/Database.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Database.cpp.i
.PHONY : src/test/common/Database.cpp.i

src/test/common/Database.s: src/test/common/Database.cpp.s

.PHONY : src/test/common/Database.s

# target to generate assembly for a file
src/test/common/Database.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Database.cpp.s
.PHONY : src/test/common/Database.cpp.s

src/test/common/Hashmap.o: src/test/common/Hashmap.cpp.o

.PHONY : src/test/common/Hashmap.o

# target to build an object file
src/test/common/Hashmap.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Hashmap.cpp.o
.PHONY : src/test/common/Hashmap.cpp.o

src/test/common/Hashmap.i: src/test/common/Hashmap.cpp.i

.PHONY : src/test/common/Hashmap.i

# target to preprocess a source file
src/test/common/Hashmap.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Hashmap.cpp.i
.PHONY : src/test/common/Hashmap.cpp.i

src/test/common/Hashmap.s: src/test/common/Hashmap.cpp.s

.PHONY : src/test/common/Hashmap.s

# target to generate assembly for a file
src/test/common/Hashmap.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Hashmap.cpp.s
.PHONY : src/test/common/Hashmap.cpp.s

src/test/common/Mmap.o: src/test/common/Mmap.cpp.o

.PHONY : src/test/common/Mmap.o

# target to build an object file
src/test/common/Mmap.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Mmap.cpp.o
.PHONY : src/test/common/Mmap.cpp.o

src/test/common/Mmap.i: src/test/common/Mmap.cpp.i

.PHONY : src/test/common/Mmap.i

# target to preprocess a source file
src/test/common/Mmap.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Mmap.cpp.i
.PHONY : src/test/common/Mmap.cpp.i

src/test/common/Mmap.s: src/test/common/Mmap.cpp.s

.PHONY : src/test/common/Mmap.s

# target to generate assembly for a file
src/test/common/Mmap.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/Mmap.cpp.s
.PHONY : src/test/common/Mmap.cpp.s

src/test/common/PartitionedDeque.o: src/test/common/PartitionedDeque.cpp.o

.PHONY : src/test/common/PartitionedDeque.o

# target to build an object file
src/test/common/PartitionedDeque.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/PartitionedDeque.cpp.o
.PHONY : src/test/common/PartitionedDeque.cpp.o

src/test/common/PartitionedDeque.i: src/test/common/PartitionedDeque.cpp.i

.PHONY : src/test/common/PartitionedDeque.i

# target to preprocess a source file
src/test/common/PartitionedDeque.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/PartitionedDeque.cpp.i
.PHONY : src/test/common/PartitionedDeque.cpp.i

src/test/common/PartitionedDeque.s: src/test/common/PartitionedDeque.cpp.s

.PHONY : src/test/common/PartitionedDeque.s

# target to generate assembly for a file
src/test/common/PartitionedDeque.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/PartitionedDeque.cpp.s
.PHONY : src/test/common/PartitionedDeque.cpp.s

src/test/common/runtime/Stack.o: src/test/common/runtime/Stack.cpp.o

.PHONY : src/test/common/runtime/Stack.o

# target to build an object file
src/test/common/runtime/Stack.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/runtime/Stack.cpp.o
.PHONY : src/test/common/runtime/Stack.cpp.o

src/test/common/runtime/Stack.i: src/test/common/runtime/Stack.cpp.i

.PHONY : src/test/common/runtime/Stack.i

# target to preprocess a source file
src/test/common/runtime/Stack.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/runtime/Stack.cpp.i
.PHONY : src/test/common/runtime/Stack.cpp.i

src/test/common/runtime/Stack.s: src/test/common/runtime/Stack.cpp.s

.PHONY : src/test/common/runtime/Stack.s

# target to generate assembly for a file
src/test/common/runtime/Stack.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/common/runtime/Stack.cpp.s
.PHONY : src/test/common/runtime/Stack.cpp.s

src/test/ssb.o: src/test/ssb.cpp.o

.PHONY : src/test/ssb.o

# target to build an object file
src/test/ssb.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/ssb.cpp.o
.PHONY : src/test/ssb.cpp.o

src/test/ssb.i: src/test/ssb.cpp.i

.PHONY : src/test/ssb.i

# target to preprocess a source file
src/test/ssb.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/ssb.cpp.i
.PHONY : src/test/ssb.cpp.i

src/test/ssb.s: src/test/ssb.cpp.s

.PHONY : src/test/ssb.s

# target to generate assembly for a file
src/test/ssb.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/ssb.cpp.s
.PHONY : src/test/ssb.cpp.s

src/test/ssb_expected.o: src/test/ssb_expected.cpp.o

.PHONY : src/test/ssb_expected.o

# target to build an object file
src/test/ssb_expected.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/ssb_expected.cpp.o
.PHONY : src/test/ssb_expected.cpp.o

src/test/ssb_expected.i: src/test/ssb_expected.cpp.i

.PHONY : src/test/ssb_expected.i

# target to preprocess a source file
src/test/ssb_expected.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/ssb_expected.cpp.i
.PHONY : src/test/ssb_expected.cpp.i

src/test/ssb_expected.s: src/test/ssb_expected.cpp.s

.PHONY : src/test/ssb_expected.s

# target to generate assembly for a file
src/test/ssb_expected.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/ssb_expected.cpp.s
.PHONY : src/test/ssb_expected.cpp.s

src/test/tpch.o: src/test/tpch.cpp.o

.PHONY : src/test/tpch.o

# target to build an object file
src/test/tpch.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/tpch.cpp.o
.PHONY : src/test/tpch.cpp.o

src/test/tpch.i: src/test/tpch.cpp.i

.PHONY : src/test/tpch.i

# target to preprocess a source file
src/test/tpch.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/tpch.cpp.i
.PHONY : src/test/tpch.cpp.i

src/test/tpch.s: src/test/tpch.cpp.s

.PHONY : src/test/tpch.s

# target to generate assembly for a file
src/test/tpch.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/tpch.cpp.s
.PHONY : src/test/tpch.cpp.s

src/test/tpch_expected.o: src/test/tpch_expected.cpp.o

.PHONY : src/test/tpch_expected.o

# target to build an object file
src/test/tpch_expected.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/tpch_expected.cpp.o
.PHONY : src/test/tpch_expected.cpp.o

src/test/tpch_expected.i: src/test/tpch_expected.cpp.i

.PHONY : src/test/tpch_expected.i

# target to preprocess a source file
src/test/tpch_expected.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/tpch_expected.cpp.i
.PHONY : src/test/tpch_expected.cpp.i

src/test/tpch_expected.s: src/test/tpch_expected.cpp.s

.PHONY : src/test/tpch_expected.s

# target to generate assembly for a file
src/test/tpch_expected.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/tpch_expected.cpp.s
.PHONY : src/test/tpch_expected.cpp.s

src/test/vectorwise/Operators.o: src/test/vectorwise/Operators.cpp.o

.PHONY : src/test/vectorwise/Operators.o

# target to build an object file
src/test/vectorwise/Operators.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/vectorwise/Operators.cpp.o
.PHONY : src/test/vectorwise/Operators.cpp.o

src/test/vectorwise/Operators.i: src/test/vectorwise/Operators.cpp.i

.PHONY : src/test/vectorwise/Operators.i

# target to preprocess a source file
src/test/vectorwise/Operators.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/vectorwise/Operators.cpp.i
.PHONY : src/test/vectorwise/Operators.cpp.i

src/test/vectorwise/Operators.s: src/test/vectorwise/Operators.cpp.s

.PHONY : src/test/vectorwise/Operators.s

# target to generate assembly for a file
src/test/vectorwise/Operators.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/vectorwise/Operators.cpp.s
.PHONY : src/test/vectorwise/Operators.cpp.s

src/test/vectorwise/primitives.o: src/test/vectorwise/primitives.cpp.o

.PHONY : src/test/vectorwise/primitives.o

# target to build an object file
src/test/vectorwise/primitives.cpp.o:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/vectorwise/primitives.cpp.o
.PHONY : src/test/vectorwise/primitives.cpp.o

src/test/vectorwise/primitives.i: src/test/vectorwise/primitives.cpp.i

.PHONY : src/test/vectorwise/primitives.i

# target to preprocess a source file
src/test/vectorwise/primitives.cpp.i:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/vectorwise/primitives.cpp.i
.PHONY : src/test/vectorwise/primitives.cpp.i

src/test/vectorwise/primitives.s: src/test/vectorwise/primitives.cpp.s

.PHONY : src/test/vectorwise/primitives.s

# target to generate assembly for a file
src/test/vectorwise/primitives.cpp.s:
	$(MAKE) -f CMakeFiles/test_all.dir/build.make CMakeFiles/test_all.dir/src/test/vectorwise/primitives.cpp.s
.PHONY : src/test/vectorwise/primitives.cpp.s

src/vectorwise/Operations.o: src/vectorwise/Operations.cpp.o

.PHONY : src/vectorwise/Operations.o

# target to build an object file
src/vectorwise/Operations.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/Operations.cpp.o
.PHONY : src/vectorwise/Operations.cpp.o

src/vectorwise/Operations.i: src/vectorwise/Operations.cpp.i

.PHONY : src/vectorwise/Operations.i

# target to preprocess a source file
src/vectorwise/Operations.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/Operations.cpp.i
.PHONY : src/vectorwise/Operations.cpp.i

src/vectorwise/Operations.s: src/vectorwise/Operations.cpp.s

.PHONY : src/vectorwise/Operations.s

# target to generate assembly for a file
src/vectorwise/Operations.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/Operations.cpp.s
.PHONY : src/vectorwise/Operations.cpp.s

src/vectorwise/Operators.o: src/vectorwise/Operators.cpp.o

.PHONY : src/vectorwise/Operators.o

# target to build an object file
src/vectorwise/Operators.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/Operators.cpp.o
.PHONY : src/vectorwise/Operators.cpp.o

src/vectorwise/Operators.i: src/vectorwise/Operators.cpp.i

.PHONY : src/vectorwise/Operators.i

# target to preprocess a source file
src/vectorwise/Operators.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/Operators.cpp.i
.PHONY : src/vectorwise/Operators.cpp.i

src/vectorwise/Operators.s: src/vectorwise/Operators.cpp.s

.PHONY : src/vectorwise/Operators.s

# target to generate assembly for a file
src/vectorwise/Operators.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/Operators.cpp.s
.PHONY : src/vectorwise/Operators.cpp.s

src/vectorwise/QueryBuilder.o: src/vectorwise/QueryBuilder.cpp.o

.PHONY : src/vectorwise/QueryBuilder.o

# target to build an object file
src/vectorwise/QueryBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/QueryBuilder.cpp.o
.PHONY : src/vectorwise/QueryBuilder.cpp.o

src/vectorwise/QueryBuilder.i: src/vectorwise/QueryBuilder.cpp.i

.PHONY : src/vectorwise/QueryBuilder.i

# target to preprocess a source file
src/vectorwise/QueryBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/QueryBuilder.cpp.i
.PHONY : src/vectorwise/QueryBuilder.cpp.i

src/vectorwise/QueryBuilder.s: src/vectorwise/QueryBuilder.cpp.s

.PHONY : src/vectorwise/QueryBuilder.s

# target to generate assembly for a file
src/vectorwise/QueryBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/QueryBuilder.cpp.s
.PHONY : src/vectorwise/QueryBuilder.cpp.s

src/vectorwise/primitives/Aggregation.o: src/vectorwise/primitives/Aggregation.cpp.o

.PHONY : src/vectorwise/primitives/Aggregation.o

# target to build an object file
src/vectorwise/primitives/Aggregation.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Aggregation.cpp.o
.PHONY : src/vectorwise/primitives/Aggregation.cpp.o

src/vectorwise/primitives/Aggregation.i: src/vectorwise/primitives/Aggregation.cpp.i

.PHONY : src/vectorwise/primitives/Aggregation.i

# target to preprocess a source file
src/vectorwise/primitives/Aggregation.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Aggregation.cpp.i
.PHONY : src/vectorwise/primitives/Aggregation.cpp.i

src/vectorwise/primitives/Aggregation.s: src/vectorwise/primitives/Aggregation.cpp.s

.PHONY : src/vectorwise/primitives/Aggregation.s

# target to generate assembly for a file
src/vectorwise/primitives/Aggregation.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Aggregation.cpp.s
.PHONY : src/vectorwise/primitives/Aggregation.cpp.s

src/vectorwise/primitives/Hash.o: src/vectorwise/primitives/Hash.cpp.o

.PHONY : src/vectorwise/primitives/Hash.o

# target to build an object file
src/vectorwise/primitives/Hash.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Hash.cpp.o
.PHONY : src/vectorwise/primitives/Hash.cpp.o

src/vectorwise/primitives/Hash.i: src/vectorwise/primitives/Hash.cpp.i

.PHONY : src/vectorwise/primitives/Hash.i

# target to preprocess a source file
src/vectorwise/primitives/Hash.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Hash.cpp.i
.PHONY : src/vectorwise/primitives/Hash.cpp.i

src/vectorwise/primitives/Hash.s: src/vectorwise/primitives/Hash.cpp.s

.PHONY : src/vectorwise/primitives/Hash.s

# target to generate assembly for a file
src/vectorwise/primitives/Hash.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Hash.cpp.s
.PHONY : src/vectorwise/primitives/Hash.cpp.s

src/vectorwise/primitives/KeyEquality.o: src/vectorwise/primitives/KeyEquality.cpp.o

.PHONY : src/vectorwise/primitives/KeyEquality.o

# target to build an object file
src/vectorwise/primitives/KeyEquality.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/KeyEquality.cpp.o
.PHONY : src/vectorwise/primitives/KeyEquality.cpp.o

src/vectorwise/primitives/KeyEquality.i: src/vectorwise/primitives/KeyEquality.cpp.i

.PHONY : src/vectorwise/primitives/KeyEquality.i

# target to preprocess a source file
src/vectorwise/primitives/KeyEquality.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/KeyEquality.cpp.i
.PHONY : src/vectorwise/primitives/KeyEquality.cpp.i

src/vectorwise/primitives/KeyEquality.s: src/vectorwise/primitives/KeyEquality.cpp.s

.PHONY : src/vectorwise/primitives/KeyEquality.s

# target to generate assembly for a file
src/vectorwise/primitives/KeyEquality.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/KeyEquality.cpp.s
.PHONY : src/vectorwise/primitives/KeyEquality.cpp.s

src/vectorwise/primitives/Partition.o: src/vectorwise/primitives/Partition.cpp.o

.PHONY : src/vectorwise/primitives/Partition.o

# target to build an object file
src/vectorwise/primitives/Partition.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Partition.cpp.o
.PHONY : src/vectorwise/primitives/Partition.cpp.o

src/vectorwise/primitives/Partition.i: src/vectorwise/primitives/Partition.cpp.i

.PHONY : src/vectorwise/primitives/Partition.i

# target to preprocess a source file
src/vectorwise/primitives/Partition.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Partition.cpp.i
.PHONY : src/vectorwise/primitives/Partition.cpp.i

src/vectorwise/primitives/Partition.s: src/vectorwise/primitives/Partition.cpp.s

.PHONY : src/vectorwise/primitives/Partition.s

# target to generate assembly for a file
src/vectorwise/primitives/Partition.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Partition.cpp.s
.PHONY : src/vectorwise/primitives/Partition.cpp.s

src/vectorwise/primitives/Projection.o: src/vectorwise/primitives/Projection.cpp.o

.PHONY : src/vectorwise/primitives/Projection.o

# target to build an object file
src/vectorwise/primitives/Projection.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Projection.cpp.o
.PHONY : src/vectorwise/primitives/Projection.cpp.o

src/vectorwise/primitives/Projection.i: src/vectorwise/primitives/Projection.cpp.i

.PHONY : src/vectorwise/primitives/Projection.i

# target to preprocess a source file
src/vectorwise/primitives/Projection.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Projection.cpp.i
.PHONY : src/vectorwise/primitives/Projection.cpp.i

src/vectorwise/primitives/Projection.s: src/vectorwise/primitives/Projection.cpp.s

.PHONY : src/vectorwise/primitives/Projection.s

# target to generate assembly for a file
src/vectorwise/primitives/Projection.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Projection.cpp.s
.PHONY : src/vectorwise/primitives/Projection.cpp.s

src/vectorwise/primitives/ScatterGather.o: src/vectorwise/primitives/ScatterGather.cpp.o

.PHONY : src/vectorwise/primitives/ScatterGather.o

# target to build an object file
src/vectorwise/primitives/ScatterGather.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/ScatterGather.cpp.o
.PHONY : src/vectorwise/primitives/ScatterGather.cpp.o

src/vectorwise/primitives/ScatterGather.i: src/vectorwise/primitives/ScatterGather.cpp.i

.PHONY : src/vectorwise/primitives/ScatterGather.i

# target to preprocess a source file
src/vectorwise/primitives/ScatterGather.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/ScatterGather.cpp.i
.PHONY : src/vectorwise/primitives/ScatterGather.cpp.i

src/vectorwise/primitives/ScatterGather.s: src/vectorwise/primitives/ScatterGather.cpp.s

.PHONY : src/vectorwise/primitives/ScatterGather.s

# target to generate assembly for a file
src/vectorwise/primitives/ScatterGather.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/ScatterGather.cpp.s
.PHONY : src/vectorwise/primitives/ScatterGather.cpp.s

src/vectorwise/primitives/Selection.o: src/vectorwise/primitives/Selection.cpp.o

.PHONY : src/vectorwise/primitives/Selection.o

# target to build an object file
src/vectorwise/primitives/Selection.cpp.o:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Selection.cpp.o
.PHONY : src/vectorwise/primitives/Selection.cpp.o

src/vectorwise/primitives/Selection.i: src/vectorwise/primitives/Selection.cpp.i

.PHONY : src/vectorwise/primitives/Selection.i

# target to preprocess a source file
src/vectorwise/primitives/Selection.cpp.i:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Selection.cpp.i
.PHONY : src/vectorwise/primitives/Selection.cpp.i

src/vectorwise/primitives/Selection.s: src/vectorwise/primitives/Selection.cpp.s

.PHONY : src/vectorwise/primitives/Selection.s

# target to generate assembly for a file
src/vectorwise/primitives/Selection.cpp.s:
	$(MAKE) -f CMakeFiles/vectorwise.dir/build.make CMakeFiles/vectorwise.dir/src/vectorwise/primitives/Selection.cpp.s
.PHONY : src/vectorwise/primitives/Selection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... test_all"
	@echo "... test"
	@echo "... tpch"
	@echo "... rebuild_cache"
	@echo "... run_tpch"
	@echo "... vectorwise"
	@echo "... hyper"
	@echo "... benchmark_config"
	@echo "... run_ssb"
	@echo "... common"
	@echo "... bench"
	@echo "... run_prim"
	@echo "... ssb"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... listevents"
	@echo "... jevents"
	@echo "... src/bench.o"
	@echo "... src/bench.i"
	@echo "... src/bench.s"
	@echo "... src/benchmarks/config.o"
	@echo "... src/benchmarks/config.i"
	@echo "... src/benchmarks/config.s"
	@echo "... src/benchmarks/primitives/run.o"
	@echo "... src/benchmarks/primitives/run.i"
	@echo "... src/benchmarks/primitives/run.s"
	@echo "... src/benchmarks/sbb/queries/q11.o"
	@echo "... src/benchmarks/sbb/queries/q11.i"
	@echo "... src/benchmarks/sbb/queries/q11.s"
	@echo "... src/benchmarks/sbb/queries/q12.o"
	@echo "... src/benchmarks/sbb/queries/q12.i"
	@echo "... src/benchmarks/sbb/queries/q12.s"
	@echo "... src/benchmarks/sbb/queries/q13.o"
	@echo "... src/benchmarks/sbb/queries/q13.i"
	@echo "... src/benchmarks/sbb/queries/q13.s"
	@echo "... src/benchmarks/sbb/queries/q21.o"
	@echo "... src/benchmarks/sbb/queries/q21.i"
	@echo "... src/benchmarks/sbb/queries/q21.s"
	@echo "... src/benchmarks/sbb/queries/q22.o"
	@echo "... src/benchmarks/sbb/queries/q22.i"
	@echo "... src/benchmarks/sbb/queries/q22.s"
	@echo "... src/benchmarks/sbb/queries/q23.o"
	@echo "... src/benchmarks/sbb/queries/q23.i"
	@echo "... src/benchmarks/sbb/queries/q23.s"
	@echo "... src/benchmarks/sbb/queries/q31.o"
	@echo "... src/benchmarks/sbb/queries/q31.i"
	@echo "... src/benchmarks/sbb/queries/q31.s"
	@echo "... src/benchmarks/sbb/queries/q32.o"
	@echo "... src/benchmarks/sbb/queries/q32.i"
	@echo "... src/benchmarks/sbb/queries/q32.s"
	@echo "... src/benchmarks/sbb/queries/q33.o"
	@echo "... src/benchmarks/sbb/queries/q33.i"
	@echo "... src/benchmarks/sbb/queries/q33.s"
	@echo "... src/benchmarks/sbb/queries/q34.o"
	@echo "... src/benchmarks/sbb/queries/q34.i"
	@echo "... src/benchmarks/sbb/queries/q34.s"
	@echo "... src/benchmarks/sbb/queries/q41.o"
	@echo "... src/benchmarks/sbb/queries/q41.i"
	@echo "... src/benchmarks/sbb/queries/q41.s"
	@echo "... src/benchmarks/sbb/queries/q42.o"
	@echo "... src/benchmarks/sbb/queries/q42.i"
	@echo "... src/benchmarks/sbb/queries/q42.s"
	@echo "... src/benchmarks/sbb/queries/q43.o"
	@echo "... src/benchmarks/sbb/queries/q43.i"
	@echo "... src/benchmarks/sbb/queries/q43.s"
	@echo "... src/benchmarks/sbb/run.o"
	@echo "... src/benchmarks/sbb/run.i"
	@echo "... src/benchmarks/sbb/run.s"
	@echo "... src/benchmarks/tpch/queries/q1.o"
	@echo "... src/benchmarks/tpch/queries/q1.i"
	@echo "... src/benchmarks/tpch/queries/q1.s"
	@echo "... src/benchmarks/tpch/queries/q18.o"
	@echo "... src/benchmarks/tpch/queries/q18.i"
	@echo "... src/benchmarks/tpch/queries/q18.s"
	@echo "... src/benchmarks/tpch/queries/q3.o"
	@echo "... src/benchmarks/tpch/queries/q3.i"
	@echo "... src/benchmarks/tpch/queries/q3.s"
	@echo "... src/benchmarks/tpch/queries/q5.o"
	@echo "... src/benchmarks/tpch/queries/q5.i"
	@echo "... src/benchmarks/tpch/queries/q5.s"
	@echo "... src/benchmarks/tpch/queries/q5_no_sel.o"
	@echo "... src/benchmarks/tpch/queries/q5_no_sel.i"
	@echo "... src/benchmarks/tpch/queries/q5_no_sel.s"
	@echo "... src/benchmarks/tpch/queries/q6.o"
	@echo "... src/benchmarks/tpch/queries/q6.i"
	@echo "... src/benchmarks/tpch/queries/q6.s"
	@echo "... src/benchmarks/tpch/queries/q9.o"
	@echo "... src/benchmarks/tpch/queries/q9.i"
	@echo "... src/benchmarks/tpch/queries/q9.s"
	@echo "... src/benchmarks/tpch/queries/qSimple.o"
	@echo "... src/benchmarks/tpch/queries/qSimple.i"
	@echo "... src/benchmarks/tpch/queries/qSimple.s"
	@echo "... src/benchmarks/tpch/run.o"
	@echo "... src/benchmarks/tpch/run.i"
	@echo "... src/benchmarks/tpch/run.s"
	@echo "... src/common/algebra/Operators.o"
	@echo "... src/common/algebra/Operators.i"
	@echo "... src/common/algebra/Operators.s"
	@echo "... src/common/algebra/Types.o"
	@echo "... src/common/algebra/Types.i"
	@echo "... src/common/algebra/Types.s"
	@echo "... src/common/runtime/Concurrency.o"
	@echo "... src/common/runtime/Concurrency.i"
	@echo "... src/common/runtime/Concurrency.s"
	@echo "... src/common/runtime/Database.o"
	@echo "... src/common/runtime/Database.i"
	@echo "... src/common/runtime/Database.s"
	@echo "... src/common/runtime/Hashmap.o"
	@echo "... src/common/runtime/Hashmap.i"
	@echo "... src/common/runtime/Hashmap.s"
	@echo "... src/common/runtime/Import.o"
	@echo "... src/common/runtime/Import.i"
	@echo "... src/common/runtime/Import.s"
	@echo "... src/common/runtime/MemoryPool.o"
	@echo "... src/common/runtime/MemoryPool.i"
	@echo "... src/common/runtime/MemoryPool.s"
	@echo "... src/common/runtime/Profile.o"
	@echo "... src/common/runtime/Profile.i"
	@echo "... src/common/runtime/Profile.s"
	@echo "... src/common/runtime/String.o"
	@echo "... src/common/runtime/String.i"
	@echo "... src/common/runtime/String.s"
	@echo "... src/common/runtime/Types.o"
	@echo "... src/common/runtime/Types.i"
	@echo "... src/common/runtime/Types.s"
	@echo "... src/hyper/codegen/Translator.o"
	@echo "... src/hyper/codegen/Translator.i"
	@echo "... src/hyper/codegen/Translator.s"
	@echo "... src/hyper/codegen/TranslatorRegistry.o"
	@echo "... src/hyper/codegen/TranslatorRegistry.i"
	@echo "... src/hyper/codegen/TranslatorRegistry.s"
	@echo "... src/hyper/codegen/operators/Map.o"
	@echo "... src/hyper/codegen/operators/Map.i"
	@echo "... src/hyper/codegen/operators/Map.s"
	@echo "... src/hyper/codegen/operators/Print.o"
	@echo "... src/hyper/codegen/operators/Print.i"
	@echo "... src/hyper/codegen/operators/Print.s"
	@echo "... src/hyper/codegen/operators/Scan.o"
	@echo "... src/hyper/codegen/operators/Scan.i"
	@echo "... src/hyper/codegen/operators/Scan.s"
	@echo "... src/test/common/Database.o"
	@echo "... src/test/common/Database.i"
	@echo "... src/test/common/Database.s"
	@echo "... src/test/common/Hashmap.o"
	@echo "... src/test/common/Hashmap.i"
	@echo "... src/test/common/Hashmap.s"
	@echo "... src/test/common/Mmap.o"
	@echo "... src/test/common/Mmap.i"
	@echo "... src/test/common/Mmap.s"
	@echo "... src/test/common/PartitionedDeque.o"
	@echo "... src/test/common/PartitionedDeque.i"
	@echo "... src/test/common/PartitionedDeque.s"
	@echo "... src/test/common/runtime/Stack.o"
	@echo "... src/test/common/runtime/Stack.i"
	@echo "... src/test/common/runtime/Stack.s"
	@echo "... src/test/ssb.o"
	@echo "... src/test/ssb.i"
	@echo "... src/test/ssb.s"
	@echo "... src/test/ssb_expected.o"
	@echo "... src/test/ssb_expected.i"
	@echo "... src/test/ssb_expected.s"
	@echo "... src/test/tpch.o"
	@echo "... src/test/tpch.i"
	@echo "... src/test/tpch.s"
	@echo "... src/test/tpch_expected.o"
	@echo "... src/test/tpch_expected.i"
	@echo "... src/test/tpch_expected.s"
	@echo "... src/test/vectorwise/Operators.o"
	@echo "... src/test/vectorwise/Operators.i"
	@echo "... src/test/vectorwise/Operators.s"
	@echo "... src/test/vectorwise/primitives.o"
	@echo "... src/test/vectorwise/primitives.i"
	@echo "... src/test/vectorwise/primitives.s"
	@echo "... src/vectorwise/Operations.o"
	@echo "... src/vectorwise/Operations.i"
	@echo "... src/vectorwise/Operations.s"
	@echo "... src/vectorwise/Operators.o"
	@echo "... src/vectorwise/Operators.i"
	@echo "... src/vectorwise/Operators.s"
	@echo "... src/vectorwise/QueryBuilder.o"
	@echo "... src/vectorwise/QueryBuilder.i"
	@echo "... src/vectorwise/QueryBuilder.s"
	@echo "... src/vectorwise/primitives/Aggregation.o"
	@echo "... src/vectorwise/primitives/Aggregation.i"
	@echo "... src/vectorwise/primitives/Aggregation.s"
	@echo "... src/vectorwise/primitives/Hash.o"
	@echo "... src/vectorwise/primitives/Hash.i"
	@echo "... src/vectorwise/primitives/Hash.s"
	@echo "... src/vectorwise/primitives/KeyEquality.o"
	@echo "... src/vectorwise/primitives/KeyEquality.i"
	@echo "... src/vectorwise/primitives/KeyEquality.s"
	@echo "... src/vectorwise/primitives/Partition.o"
	@echo "... src/vectorwise/primitives/Partition.i"
	@echo "... src/vectorwise/primitives/Partition.s"
	@echo "... src/vectorwise/primitives/Projection.o"
	@echo "... src/vectorwise/primitives/Projection.i"
	@echo "... src/vectorwise/primitives/Projection.s"
	@echo "... src/vectorwise/primitives/ScatterGather.o"
	@echo "... src/vectorwise/primitives/ScatterGather.i"
	@echo "... src/vectorwise/primitives/ScatterGather.s"
	@echo "... src/vectorwise/primitives/Selection.o"
	@echo "... src/vectorwise/primitives/Selection.i"
	@echo "... src/vectorwise/primitives/Selection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

